### ISSUE TITLE
Add weapons

### ISSUE THREAD

**Issue by slithy** [slithy/bambleweeny#10]
Weapons have special properties such as damage, range and ammunition type.

Ranged weapons can have a default ammo type (e.g. "sling" -> "stone") which should be changeable by the player ("sling" -> "rock")

Weapons can be wielded. Non-wielded weapons are carried but cannot be used.

Weapons can be one or two handed. Use of a shield is incompatible with wielding 2-handed weapons, including bows.

Dual wielding is possible but with restrictions on which weapons can be wielded simultaneously.

**Comment by cattabiani** [comment]
shields are a corner case: you cannot dual wield if you are using a shield. You cannot wear 2 shields

**Comment by slithy** [comment]
This is already handled by the `hands` property. Characters have 2 free hands. A shield or a one-handed weapon has `hands=1`, a bow or two-handed weapon has `hands=2`. You cannot wear or wield items in excess of your free hands.

This doesn't stop you wearing two shields, but if you do wear two shields you have no free hands to wield any weapon.
