### ISSUE TITLE
Misleading feature: after !create and !assign the character does not show any prime

### ISSUE THREAD

**Issue by cattabiani** [slithy/bambleweeny#2]
However, you already chose a class (and a prime). This results in players assigning 2 primes (or 3 for humans) and an error message when they need to assign only one (or 2 for humans). I suggest to add the prime after !create and !assign and to not throw the error if one of the primes is the class prime

**Comment by slithy** [comment]
b75e0af fixes assign class prime at character generation

**Comment by slithy** [comment]
e5c0963 fixes No error if class prime is specified in !prime
