### ISSUE TITLE
Add calendar

### ISSUE THREAD

**Issue by slithy** [slithy/bambleweeny#31]
Add Greyhawk calendar, date tracking and phases of the moon:

https://calendars.wikia.org/wiki/Greyhawk_Calendar

**Comment by cattabiani** [comment]
Just to understand: for a moon with a period of 91 days (not divisible by 4 or 2) how many days one phase lasts? Can I just consider 8 phases divided evenly?

**Comment by slithy** [comment]
> Just to understand: for a moon with a period of 91 days (not divisible by 4 or 2) how many days one phase lasts? Can I just consider 8 phases divided evenly?

Yes, makes sense. The key thing is that the full moon occurs on the middle day of the four annual festivals.
